### ISSUE TITLE
Setting the mode-line height larger than frame-char-height  ...

### ISSUE THREAD

**Issue by jasonm23** [sabof/svg-mode-line-themes#2]
Not sure this is possible (but it would make smlt very awesome)

Setting the height to a value other than `frame-char-height` seems to make the smlt modeline disappear.  

```
(let (( width (smt/window-pixel-width))
        ( height (frame-char-height)))
```

**Comment by jasonm23** [comment]
FYI I'm finally in the process of making a theme. (I know, took me a minute!)

![screen shot 2015-04-23 at 12 02 13 am](https://cloud.githubusercontent.com/assets/71587/7279100/0f1fd7b0-e94c-11e4-887a-0dea1003655a.png)

![screen shot 2015-04-23 at 12 01 39 am](https://cloud.githubusercontent.com/assets/71587/7279101/0f206f68-e94c-11e4-92bd-d9481a1c2462.png)

**Comment by jasonm23** [comment]
[Full screen shot 2015-04-23 at 12 05 03 am](https://cloud.githubusercontent.com/assets/71587/7279157/7d53f446-e94c-11e4-94c7-cf9719c7012c.png)

**Comment by sabof** [comment]
Looks good

**Comment by jasonm23** [comment]
Thanks @sabof - the smt package is pretty nicely put together, kudos.

**Comment by jasonm23** [comment]
http://www.reddit.com/r/emacs/comments/33kiwn/work_in_progress_svg_modeline_using_sabofs_svg/

**Comment by sabof** [comment]
It should be possible to load an external file for the triangle mesh.

**Comment by jasonm23** [comment]
Ah, I was wondering.  Just use a url link yes?

**Comment by sabof** [comment]
The below worked for PNGs, I'd think it could work for SVGs as well.
```
<image id="image" x="10" y="10" width="100" height="45"
  xlink:href="http://www.gnu.org/graphics/behroze/behroze-gnu-button1.png" />
```

**Comment by jasonm23** [comment]
My only reservation with using external image files is to avoid dependency.  The obvious problem being offline or non *nix users having different path to home.  Actually, come to think of it OS X and Linux users are going to have issues with file:/// refs (/Users/ vs /home/)

 I'll see how it works out.

**Comment by sabof** [comment]
You could generate the path. `(or load-file-name buffer-file-name)` gives you the path of the current file

**Comment by jasonm23** [comment]
Right

**Comment by jasonm23** [comment]
We'd need `:xmlns:xlink "http://www.w3.org/1999/xlink"` in `smt/t-export-default-xml`

**Comment by jasonm23** [comment]
otherwise it works nicely

**Comment by jasonm23** [comment]
(added a PR for this)
